// <auto-generated />
using System;
using ComunidadeAtiva.Infra.Data.DbContextFiles;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComunidadeAtiva.Infra.Data.Migrations
{
    [DbContext(typeof(IdentityFileDbContext))]
    [Migration("20230428150031_updateChaves")]
    partial class updateChaves
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.CorpoDirigenteAssociacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("IdAssociacao")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("IdCargo")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("corpoDirigenteAssociacao");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.MoradorBeneficioSocial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("BeneficioSocialId")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("MoradorId")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("id");

                    b.HasIndex("MoradorId")
                        .IsUnique();

                    b.ToTable("moradorBeneficioSocial");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.MoradorNecessidadeEspecial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("MoradorId")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<int>("NecessidadeId")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("MoradorId")
                        .IsUnique();

                    b.ToTable("moradorNecessidadeEspecial");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.MoradorPrograma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("MoradorId")
                        .HasMaxLength(6)
                        .HasColumnType("int");

                    b.Property<int>("ProgramaId")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("MoradorId")
                        .IsUnique();

                    b.ToTable("moradorPrograma");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Associacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoFimMandato")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<int>("AnoPosse")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Email")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("NomeFantasia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Representante1")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Representante2")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("site")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("associacao");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.AssociacaoCargo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoCargo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NivelAcesso")
                        .HasMaxLength(1)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("associacaoCargo");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.AssociacaoEvento", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnoEvento")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<decimal>("CustoEstimado")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("DelegadoAssociacao")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<string>("DescricaoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MesEvento")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<string>("MoradorSolicitante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("NumeroParticipanteEstimado")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("associacaoEvento");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.AssociacaoPatrimonio", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAquisicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("DescricaoPatrimonio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Tipo")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<decimal>("ValorEstimado")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("id");

                    b.ToTable("associacaoPatrimonio");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.AssociacaoPrograma", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("DescricaoPrograma")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomePrograma")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("associacaoPrograma");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Associado", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("IdMorador")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("NumeroItentificacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("id");

                    b.ToTable("associado");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.BeneficioSocial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("DescricaoBeneficioSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeBeneficioSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("id");

                    b.ToTable("beneficioSocial");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Dependente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("IdMoradorDependente")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("IdMoradorMaster")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("dependente");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Morador", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Nascimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValue(new DateTime(1900, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroCasa")
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.Property<string>("Rg")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("RuaId")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("Situacao")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Ativo");

                    b.HasKey("id");

                    b.HasIndex("RuaId");

                    b.ToTable("morador");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.NecessidadeEspecial", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DescricaoNecessidadeEspecial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NecessitaRemedioControlado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Permanete")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.HasKey("id");

                    b.ToTable("necessidadeEspecial");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Rua", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AgenteSaudeResponsval")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Agua")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Calcada")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ColetaLixo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Energia")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Nome1")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Saneamento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.HasKey("id");

                    b.ToTable("rua");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.MoradorBeneficioSocial", b =>
                {
                    b.HasOne("ComunidadeAtiva.Dominio.Entity.Morador", null)
                        .WithOne("beneficioSocial")
                        .HasForeignKey("ComunidadeAtiva.Dominio.Entidades.MoradorBeneficioSocial", "MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.MoradorNecessidadeEspecial", b =>
                {
                    b.HasOne("ComunidadeAtiva.Dominio.Entity.Morador", null)
                        .WithOne("necessidadeEspecial")
                        .HasForeignKey("ComunidadeAtiva.Dominio.Entidades.MoradorNecessidadeEspecial", "MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entidades.MoradorPrograma", b =>
                {
                    b.HasOne("ComunidadeAtiva.Dominio.Entity.Morador", null)
                        .WithOne("programa")
                        .HasForeignKey("ComunidadeAtiva.Dominio.Entidades.MoradorPrograma", "MoradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Morador", b =>
                {
                    b.HasOne("ComunidadeAtiva.Dominio.Entity.Rua", "rua")
                        .WithMany()
                        .HasForeignKey("RuaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rua");
                });

            modelBuilder.Entity("ComunidadeAtiva.Dominio.Entity.Morador", b =>
                {
                    b.Navigation("beneficioSocial")
                        .IsRequired();

                    b.Navigation("necessidadeEspecial")
                        .IsRequired();

                    b.Navigation("programa")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
